ALTER TABLE public.international_results
  ADD COLUMN IF NOT EXISTS sf1 text,
  ADD COLUMN IF NOT EXISTS sf1_coach text,
  ADD COLUMN IF NOT EXISTS sf2 text,
  ADD COLUMN IF NOT EXISTS sf2_coach text,
  ADD COLUMN IF NOT EXISTS qf1 text,
  ADD COLUMN IF NOT EXISTS qf1_coach text,
  ADD COLUMN IF NOT EXISTS qf2 text,
  ADD COLUMN IF NOT EXISTS qf2_coach text,
  ADD COLUMN IF NOT EXISTS qf3 text,
  ADD COLUMN IF NOT EXISTS qf3_coach text,
  ADD COLUMN IF NOT EXISTS qf4 text,
  ADD COLUMN IF NOT EXISTS qf4_coach text;